### ISSUE TITLE
I hope this project is alive

### ISSUE THREAD

**Issue by jkim5959** [b0o/snag#5]
Seems like this is the only project that lets you take screenshots of workspaces.

I wish there was an install manual.

**Comment by b0o** [comment]
It's alive, I use it almost every day!

For now, the easiest way to install it is:

1. Clone the repo to the location of your choice 
    - For example, `git clone https://github.com/b0o/snag ~/code/snag`
2. Make a symbolic link to the `snag` script somewhere in your `PATH`
    - Assuming that `~/.local/bin` is in your `PATH`, run `ln -s ~/code/snag/snag ~/.local/bin/snag`
3. Now you should be able to run `snag --help`
4. If you want to create a key binding in sway, something like this should work:
    - `bindsym Mod4+Print exec snag --rofi --dir ~/screenshots/`

I'm happy to provide more help if needed.

**Comment by jkim5959** [comment]
Chad
